#!/usr/bin/bash
echo "Emotycon v1.0"
echo "😃 🙁 👍 👎 💗 💔"
echo "🐶 🐱 🐷 🦁 🐨 🐼"
echo "👨 👩 👴 👵 👦 👧"
echo "👍 👎 👆 👇 👉 👈"
echo "🎈 🎉 📱 💻 🔬 🔭"
echo "🎵 🎹 🎻 🎸 🎷 🎺"
echo "🍕 🍔 🍟 🍧 🎂 🧁"
echo "🥝 🍓 🍎 🍒 🍇 🥭"
echo "🍅 🥕 🥔 🥒 🍆 🥬"
echo "🌻 🌺 🌹 🌼 🥀 💐"
echo "🚗 🚒 🚈 🚌 🚁 🚜"
echo "⛰️  🌋 🌎 🏜️ 🏝️   🌊"
echo "🌞 🌙 🌝 🪐 ⭐ 🌠"
echo "🌞 🌤️ 🌦️ 🌧   🌈 🌨️"
echo "🔰 💢 💤 🔤 💲 🆗"
